name: CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: |
          sudo apt install -y git wget flex bison gperf python3 python3-pip python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0

      - name: Install esp-idf
        run: |
          mkdir -p ~/esp
          cd ~/esp
          git clone -b v4.4 --recursive https://github.com/espressif/esp-idf.git
          cd esp-idf
          ./install.sh

      - name: Build test_app
        run: |
          . ~/esp/esp-idf/export.sh
          idf.py set-target esp32c3
          idf.py build
          mkdir ESP32-C3-BIN
          cp build/partition_table/partition-table.bin ESP32-C3-BIN/partition-table.bin
          cp build/*.bin ESP32-C3-BIN/

      - name: Upload Firmware
        uses: actions/upload-artifact@v2
        with:
          name: ESP-TEST-C3
          path: build/*.bin
