name: CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          sudo apt install -y git wget flex bison gperf python3 python3-pip python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0

      - name: Install esp-idf
        run: |
          mkdir -p ~/esp
          cd ~/esp
          git clone -b v4.4 --recursive https://github.com/espressif/esp-idf.git
          cd esp-idf
          ./install.sh

      - name: Build
        run: |
          . ~/esp/esp-idf/export.sh
          idf.py set-target esp32c3
          idf.py build
          esptool.py --chip esp32c3 merge_bin -o test_flash_c3.bin --flash_mode dio --flash_freq 80m --flash_size 2MB 0x0 build/bootloader/bootloader.bin 0x8000 build/partition_table/partition-table.bin 0x10000 build/uart_test.bin
          mkdir ESP32-C3-BIN
          cp test_flash_c3.bin ESP32-C3-BIN/
          cp build/partition_table/partition-table.bin ESP32-C3-BIN/partition-table.bin
          cp build/*.bin ESP32-C3-BIN/

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ESP32-C3-BIN
          path: ESP32-C3-BIN/
