name: ci

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'latest'
          - 'v4.4'
          - 'v4.3'
        chip:
          - 'esp32c3'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            submodules: 'recursive'

      - name: ESP-IDF-CI
        uses: Qitas/idf-action@main
        with:
            esp_idf_version: ${{ matrix.version }}
            target: ${{ matrix.chip }}
            path: .

      - name: Package
        run: |
          mkdir BIN
          cp build/bootloader/bootloader.bin BIN/
          cp build/partition_table/partition-table.bin BIN/
          cp build/*.bin BIN/
          cp build/*.elf BIN/

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: test-${{ matrix.chip }}-${{ matrix.version }}
          path: BIN/
