name: ci

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'latest'
          - 'v4.4'
          - 'v4.3'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            submodules: 'recursive'

      - name: ESP-IDF
        uses: espressif/esp-idf-ci-action@main
        with:
            esp_idf_version: ${{ matrix.version }}
            target: esp32c3
            path: .

      - name: Package
        run: |
          esptool.py --chip esp32c3 merge_bin -o test_flash_c3.bin 0x0 build/bootloader/bootloader.bin 0x8000 build/partition_table/partition-table.bin 0x10000 build/uart_test.bin
          mkdir ESP32-C3-BIN
          cp test_flash_c3.bin ESP32-C3-BIN/
          cp build/bootloader/bootloader.bin ESP32-C3-BIN/
          cp build/partition_table/partition-table.bin ESP32-C3-BIN/
          cp build/*.bin ESP32-C3-BIN/
          cp build/*.elf ESP32-C3-BIN/

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: TEST-ESP32-C3-CI-BIN
          path: ESP32-C3-CI-BIN/
